### ISSUE TITLE
Updated Dynamo DB schema?

### ISSUE THREAD

**Issue by scottefein** [guardian/bonobo#103]
Trying out Bonobo... While I've got it up and running w/local DynamoDB, finding some Dynamo fields that don't exist (probably because I just used what you had in the cloud formation file).

Is there a place I could find an updated schema?

Cheers!

**Comment by LATaylor-guardian** [comment]
Hi Scott,

If you take a look at https://github.com/guardian/bonobo/tree/master/integration-test/scala/integration/fixtures there are three fixtures which create the tables for our integration tests which may be of help to you, namely:

 - BonoboUserTableFixture.scala
 - BonoboLabelsTableFixture.scala
 - BonoboKeysTableFixture.scala

Let us know if you have any further questions!

Thanks.

**Comment by scottefein** [comment]
Thanks!
